name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "pb.kvspace.cf"
custom_domain = true

[[kv_namespaces]]
binding = "PASTEBIN"  # do not touch this
id = "8186825955f442d48d0ece61f5abc91e"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://pb.kvspace.cf"

# url to repo, displayed in index page
REPO = ""

# url to favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "BOBOTOY"

# the email displayed in TOS
TOS_MAIL = ""

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
